name: Continuous Integration
on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cq:
    name: Codebase Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Run Formatter Check
        run: cargo fmt --all -- --check

      - name: Run Clippy Check
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run Tests
        run: cargo test --all-features

      - name: Build binary
        run: |
          cargo build
          chmod +x ./target/debug/mate

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: mate
          path: ./target/debug/mate

  ti:
    name: Tasks Integrity
    needs: cq
    strategy:
      matrix:
        include:
          - task: fibonacci
            args: "10"
          - task: http
            args: '{"api_url":"https://httpbin.org/post","data":{"sample_key":"sample_value"}}'
          - task: sum
            args: "[1, 2, 3, 4, 5]"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly

      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Install Target on Toolchain
        run: rustup target add wasm32-wasip2 --toolchain nightly

      - name: Setup Just
        uses: extractions/setup-just@v3

      - name: Build Wasm Task
        run: just build-task ${{ matrix.task }}

      - name: Download Binary
        uses: actions/download-artifact@v7
        with:
          name: mate
          path: ./bin

      - name: Run Task
        run: |
          chmod +x ./bin/mate
          ./bin/mate task run \
            --source ./${{ matrix.task }}.wasm \
            --args '${{ matrix.args }}'

  build-binaries:
    name: Build binaries
    strategy:
      matrix:
        include:
          - name: linux-x64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - name: linux-arm64
            os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - name: macos-arm64
            os: macos-latest
            target: aarch64-apple-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Build for ARM64 Linux GNU
        if: ${{ matrix.target == 'aarch64-unknown-linux-gnu' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu
          cargo build --release --target ${{ matrix.target }}

      - name: Build binary
        if: ${{ matrix.target != 'aarch64-unknown-linux-gnu' }}
        run: cargo build --release
